# Site settings
name: 'Henry Kupty'
url: 'https://hkupty.github.io'
baseurl: '/'
repository: 'hkupty/hkupty.github.io'
# disqus_shortname: 'your-disqus-name'

theme_settings:
  title: 'A monomorphic mapping of Ideas → Text'
  avatar: 'assets/images/me.jpg'
  description: 'Whatever comes to mind transformed into text, whenever I can write.'
  header_text_feature_image: assets/images/heading.jpg
  footer_text: Copyright 2017
  google_analytics: 'UA-74370609-1'
  katex: true
  rss: true
  email_address: hkupty@gmail.com
  linkedin: https://www.linkedin.com/in/hkupty
  portfolio: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

author:
  name: 'hkupty'
  email: hkupty@gmail.com
  bio: 'Self-taught engineer'
  linkedin: hkupty
  bitbucket: hkupty
  github: hkupty
  gitlab: ingvij
  stackoverflow: ingvij
  twitter: ingvijk

read_time: true

social:
  links:
    - "https://twitter.com/ingvijk"
    - "https://www.linkedin.com/in/hkupty"
    - "https://github.com/hkupty"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Build settings
destination: _site
paginate: 10
paginate_path: /recent/page:num/
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
breadcrumbs: true
read_time: true

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['Gemfile']

remote_theme: Sylhare/Type-on-Strap

compress_html:
  clippings: all
