# Site settings
title: 'Thoughts on code'
name: 'Henry Kupty'
url: 'https://hkupty.github.io'
baseurl: '/'
repository: 'hkupty/hkupty.github.io'
# disqus_shortname: 'your-disqus-name'

theme_settings:
  author: 'Henry John Kupty'
  title: 'Thoughts on code'
  avatar: 'assets/images/me.jpg'
  description: 'Whatever comes to mind transformed into text, whenever I can write.'
  header_text: "<br /><br /> Software Engineering et al<br /><br />"
  header_text_feature_image: assets/images/rooftops.jpg
  footer_text: Copyright 2017
  google_analytics: 'UA-74370609-1'
  katex: true
  rss: true
  portfolio: false
  tags: true
  email_address: hkupty@gmail.com
  linkedin: https://www.linkedin.com/in/hkupty
  github: "hkupty"
  bitbucket: hkupty
  github: hkupty
  gitlab: ingvij
  # stackoverflow: ingvij
  twitter: ingvijk
  reddit: ingvij
  #  steam: hkupty

author:
  name: 'hkupty'
  email: hkupty@gmail.com
  bio: 'Self-taught engineer'
  linkedin: hkupty

read_time: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

destination: _site
paginate: 10
paginate_path: /recent/page:num/
permalink: /:year/:title/
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

exclude: ['Gemfile']
plugins: [jekyll-paginate, jekyll-seo-tag]
remote_theme: jekyller/jasper2
