# Site settings
title: Henry Kupty
description: 'Den of Hkupty'
url: 'http://hkupty.github.io'
baseurl: '/'
google_analytics: 'UA-74370609-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'hkupty'
  email: hkupty@gmail.com
  twitter_username: ingvijk
  github_username:  hkupty
  linkedin_username:  hkupty

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'single'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['Gemfile']

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
