# Site settings
title: 'Thoughts on code'
title_separator: "|"
  name: 'Henry Kupty'
url: 'https://hkupty.github.io'
baseurl: '/'
repository: 'hkupty/hkupty.github.io'

site:
  description: 'Whatever comes to mind transformed into text, whenever I can write.'
  tags: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: 'UA-74370609-1'

twitter:
  username: ingvijk

author:
  name: 'hkupty'
  bio: 'Self-taught engineer'
  location: "Stockholm, Sweden"
  links:
    - label: @ingvijk
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ingvijk"
    - label: hkupty
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hkupty"
    - label: ingvij
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/ingvij"
    - label: hkupty
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hkupty/"

destination: _site
paginate: 10
paginate_path: /recent/page:num/
permalink: /:year/:title/
breadcrumbs: true

kramdown:
  input: GFM
  hard_wrap: false

exclude: ['Gemfile']
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
